// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutComp: typeof import('./src/components/AboutComp.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DetailComp: typeof import('./src/components/DetailComp.vue')['default']
    FloatControl: typeof import('./src/components/FloatControl.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    LogoComp: typeof import('./src/components/LogoComp.vue')['default']
    MapComp: typeof import('./src/components/MapComp.vue')['default']
    ModalComp: typeof import('./src/components/ModalComp.vue')['default']
    NavComp: typeof import('./src/components/NavComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComp: typeof import('./src/components/SearchComp.vue')['default']
  }
}

export { }
