name: Cafe Sync

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get source sha
        run: curl https://api.github.com/repos/Lanseria/awesome-cn-data/branches/sampling-point --silent | grep "sha" | head -n1 > sha

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: 'chore: 每日更新 github 分支为 sampling-point 的数据，存 sha [bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
