name: Cafe Sync

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get source sha
        run: curl https://api.github.com/repos/Lanseria/awesome-cn-data/branches/sampling-point --silent | grep "sha" | head -n1 > sha 

      - name: Update source sha
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: 每日更新 github 分支为 sampling-point 的数据，存 sha [bot]"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
